syntax on
filetype plugin indent on
autocmd BufNewFile,BufFilePre,BufRead *.md set filetype=markdown

let &rtp .= ',~/.config/vim'
runtime! vimrc.d/*.vim
set runtimepath+=n$XDG_CONFIG_HOME/vim,n$XDG_CONFIG_HOME/vim/after
set viminfofile=$XDG_STATE_HOME/vim/viminfo

colorscheme gruvbox
" Transparent background
	highlight! Normal ctermbg=NONE guibg=NONE
	highlight! NonText ctermbg=NONE guibg=NONE
