# ~/.bashrc: executed by bash(1) for non-login shells.
# based on Pop!_OS defaults at ./bashrc_old

# If not running interactively, don't do anything
case $- in
	*i*) ;;
	  *) return;;
esac

shopt -s autocd			# Automatically cd into typed directory
stty stop undef			# Disable ctrl-s to freeze terminal
shopt -s checkwinsize	# Check window sizes after each command
shopt -s globstar		# Use the pattern "**" to find all files and subdirectories

HISTSIZE=10000
HISTFILESIZE=2000
HISTFILE="${XDG_CACHE_HOME:-$HOME/.cache}/bash/history"
HISTCONTROL=ignoreboth	# Don't duplicate lines of lines starting with space
shopt -s histappend		# Append to history, don't overwrite it

# Load aliases and shortcuts if existent
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliasrc" ] && \
	source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliasrc" \
|| \
	{ [ -f "$HOME/.bash_aliases" ] && \
		source "$HOME/.bash_aliases"; }


# Enable programmable completion features 
shopt -oq posix || {
	[ -f /usr/share/bash-completion/bash_completion ] && \
		source /usr/share/bash-completion/bash_completion \
	|| \
	[ -f /etc/bash_completion ] && \
		source /etc/bash_completion;
}


# make LESS(1) more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && \
	eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
[ -z "${debian_chroot:-}" ] && \
	[ -r /etc/debian_chroot ] && \
		debian_chroot=$(cat /etc/debian_chroot)

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# colored prompt, if the terminal has the capability
force_color_prompt=yes

[ -n "$force_color_prompt" ] && [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null && {
	# If color is supported; assume it's compliant with Ecma-48
	color_prompt=yes
} || { 
	color_prompt=
}

[ "$color_prompt" = yes ] && \
	PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ ' \
|| \
	PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
unset color_prompt force_color_prompt

# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'


# If this is an xterm set the title to user@host:dir
[ "$TERM" = xterm ] || [ "$TERM" = rxvt ] && \
	PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"

# tput(1) variables for colored less(1) and man(1) output:
export LESS="--RAW-CONTROL-CHARS"
export MANPAGER="less --LONG-PROMPT --squeeze-blank-lines"
[ -n "$TERM" ] && \
	[ -f  "${XDG_CONFIG_HOME:-$HOME/.config}/shell/LESS_TERMCAP" ] && \
		source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/LESS_TERMCAP"
export GROFF_NO_SGR=1		# for konsole and gnome-terminal


# Set up fzf(1) key bindings and fuzzy completion if supported
command -v "fzf" > /dev/null 2>&1 && {
	# Check if fzf(1) version is more or equal to 0.48.0 (required for fzf --bash)
	printf "0.48.0\n%s" "$(fzf --version 2>/dev/null | cut -d ' ' -f1)" | sort --version-sort --check && {
		command -v "fd" > /dev/null 2>&1 && {
			# Set fd(1) as default source for fzf
			export FZF_DEFAULT_COMMAND="fd --strip-cwd-prefix --hidden --follow --type file" # Not used by shell integration
			export FZF_CTRL_T_COMMAND="fd --hidden --follow --type file"
			export FZF_ALT_C_COMMAND="fd --hidden --follow --type directory"

			# The first argument to the function ($1) is the base path to start traversal
			# Completion source for path completion (e.g. vim **<TAB>)
			_fzf_compgen_path() { fd --hidden --follow --exclude ".git" . "$1"; }
			# Completion source for directory completion (e.g. cd **<TAB>)
			_fzf_compgen_dir() { fd --hidden --follow --type directory --exclude ".git" . "$1"; }
		} 
	export FZF_CTRL_R_COMMAND="" # Disabled

	export FZF_DEFAULT_OPTS="--style=minimal --layout=reverse --height=~40% --info=inline-right --no-scrollbar --no-separator"
	export FZF_CTRL_T_OPTS="--select-1 --exit-0 $(
		# Preview files with fzf-preview.sh which utilizes bat(1), chafa(1), imgcat(1) if installed
		command -v fzf-preview.sh > /dev/null 2>&1 && \
			echo -n "--preview='fzf-preview.sh {}' --bind 'focus:transform-header:file --brief {}'"
		)"
	export FZF_ALT_C_OPTS="$(
		# Preview directories with tree(1) if installed
		command -v tree > /dev/null 2>&1 && {
			echo -n '--preview "tree -a -L 2 --gitignore --noreport --filelimit 250 -F -C {}"'
		} || echo -n '--preview "ls -A -F {}"' # Or else fall back to ls(1)
	)"

	# Options to fuzzy completion
	export FZF_COMPLETION_OPTS="--style minimal --info=inline-right"
	# Options for path completion (e.g. vim **<TAB>)
	export FZF_COMPLETION_PATH_OPTS=""
	# Options for directory completion (e.g. cd **<TAB>)
	export FZF_COMPLETION_DIR_OPTS="--walker dir,follow,hidden"

	eval "$(fzf --bash)"
	}
}
